/** Villes du Maroc (liste déroulante profil). */
export const MOROCCO_CITIES = [
  "Agadir",
  "Al Hoceima",
  "Asilah",
  "Azemmour",
  "Azrou",
  "Beni Mellal",
  "Berkane",
  "Berrechid",
  "Boujdour",
  "Bouskoura",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Fnideq",
  "Guelmim",
  "Ifrane",
  "Kénitra",
  "Khemisset",
  "Khouribga",
  "Ksar El Kebir",
  "Larache",
  "Laâyoune",
  "Marrakech",
  "Martil",
  "Meknès",
  "Midelt",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Oued Zem",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Sefrou",
  "Settat",
  "Sidi Bennour",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Slimane",
  "Skhirat",
  "Tanger",
  "Tan-Tan",
  "Taourirt",
  "Taroudant",
  "Taza",
  "Témara",
  "Tétouan",
  "Tiznit",
  "Youssoufia",
] as const;

export type MoroccoCity = (typeof MOROCCO_CITIES)[number];
